title = "Moderation"

[[rule]]
title = "Reporting"
description = """
Moderators are here to help. If there is a problem that needs Moderator attention, please create a ticket. Any and all problems are discussed as a group among Moderators. Remember nothing can be reported without concrete proof. Reporting because of rumors or hearsay is not acceptable proof. Please provide context, and searchable/linkable information as well as identifying information such as Member IDs.
"""

[[rule]]
title = "Consistency"
description = """
All rules apply to all Members, including Moderators. If the Community has reason to believe the Owner is unfit for ownership due to breaching any rules defined in this document or misusing the server outside of what is listed, the Community may request for ownership to be removed and changed.
"""

[[rule]]
title = "Transparency"
description = """
Audit Logs are visible to all server Members. Audit Logs contain a history of all changes and actions within the server as well as all Moderator actions such as punishments given to Members.
"""

[[rule]]
title = "Enforcement"
description = """
Enforcement of these rules may be done through different means. Listed below are the typical forms.

#### Case by Case

With Case by Case moderation, punishment is more subjective and dependent on the nature and frequency of transgressions. While this system gives Moderators a large amount of flexibility, accountability can be difficult due to the lack of standards and certain Moderators may punish Members differently. Because of this, all Moderator actions are free to audit and review and may require further agreement from the Moderation team.

#### Automod

Basic auto moderation will exist in this server to prevent universally severe and hateful/offensive language. If auto moderation prevents natural discussion at any point, report the issue via ticket. Additionally, basic safety and security precautions will exist to filter out harmful links and material shared within this server.
"""

[[rule]]
title = "Punishment"
description = """
#### 3.5.a - Moderator Privileges
If a Member is found breaking any of these rules,
Moderators reserve the right to give any of the following punishments depending on the severity of the offense:

* **Warnings**
  * Warnings act as a permanent history for Members and their behavior. Warnings should be descriptive and provide context or reason.
* **Timeouts**
  * Timeouts act as a temporary safeguard against in the moment disruption of the server and allow Members to “cool off” until they mitigate the current situation with a Moderator.
*	**Jail**
  * Jail is often used to hold a member temporarily, especially if a situation is ongoing. It’s used as a way to let members cool off, wait for a ticket to be made, and/or handle things without disrupting chat. Jails are also used if a member doesn’t answer their ticket after 48 hours.
*	**Snippetban**
  * Snippetbans are typically never used. It’s a punishment that can be temporary or permanent and prevents a member from creating or managing snippets.
*	**Pollban**
  * Pollbans are typically never used. It’s a punishment that can be temporary or permanent and prevents a member from creating polls.
* **Kicks**
  * Kicks are typically not used within this server due to the way rule breaking is handled.
* **Bans**
  * Bans may either act as a temporary punishment for an allotted time frame based on the severity of the offense and the offender's history or as a permanent punishment.

#### 3.5.b - Administrator Privileges
Administrators outline and uphold our standards.

* **Dispute regarding conduct**
  * Administrators are permitted to resolve disputes regarding the Code of Conduct by using context, perspective and interpretation to ensure order.
* **Internal and External**
  * Administrators are permitted to investigate internal and external interests and speak for the organization.

#### 3.5.c - Problematic Behavior
If a member is deemed problematic, moderators reserve the right to punish members more strictly. This includes “final warnings” and, in severe cases, bans. 
Problematic behavior can be defined by a variety of factors. This includes, but not limited to:
* Lengthy moderation logs, including verbal warns
* Extensive ticket history
* Constantly “pushing the line” of rules
* Lack of improvement from previous punishments
* Members recognized to be problematic in other spaces (crossbans)
"""

[[rule]]
title = "Punishment Evasion"
description = """
Members should not attempt to evade the consequences of their actions such as using an alternate account to bypass restrictions. Punishment evasion will result in an immediate ban.
"""

[[rule]]
title = "Fairness"
description = """
The rules defined in this document are to be reviewed and agreed upon by the Community as a whole. If a rule is unclear, it is to be revised until it is clear. If a Member believes that this document is missing any rules or exceptions, the Member may request for this addition to be reviewed and agreed upon by the Community.

In the event of a Moderator using personal best judgment when dealing with Members and punishments, all Members have the right to audit said actions and the Moderator should provide justification and or seek unanimous approval from the Moderation team.
"""

[[rule]]
title = "Appeals"
description = """
* If a Member believes their punishment is unfair, the Member can discuss their warning with the Moderation team via ticket.
* If a Member has been temporarily or permanently banned from the server and thus cannot create a ticket, the Member may reach out directly to the Moderation team for appeal.
* Appeals currently are managed via Wick and can be accessed at https://appeals.wickbot.com/.
"""